# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_graphique.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 447)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.choix_projet = QtWidgets.QComboBox(Dialog)
        self.choix_projet.setEnabled(True)
        self.choix_projet.setMouseTracking(False)
        self.choix_projet.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.choix_projet.setObjectName("choix_projet")
        self.choix_projet.addItem("")
        self.choix_projet.addItem("")
        self.choix_projet.addItem("")
        self.choix_projet.addItem("")
        self.choix_projet.addItem("")
        self.verticalLayout.addWidget(self.choix_projet)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ligne_chemin = QtWidgets.QLineEdit(Dialog)
        self.ligne_chemin.setObjectName("ligne_chemin")
        self.horizontalLayout_2.addWidget(self.ligne_chemin)
        self.choix_chemin = QtWidgets.QPushButton(Dialog)
        self.choix_chemin.setObjectName("choix_chemin")
        self.horizontalLayout_2.addWidget(self.choix_chemin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.bouton_import = QtWidgets.QPushButton(Dialog)
        self.bouton_import.setObjectName("bouton_import")
        self.verticalLayout.addWidget(self.bouton_import)
        self.ligne_info = QtWidgets.QLabel(Dialog)
        self.ligne_info.setObjectName("ligne_info")
        self.verticalLayout.addWidget(self.ligne_info)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.bouton_fermer = QtWidgets.QPushButton(Dialog)
        self.bouton_fermer.setObjectName("bouton_fermer")
        self.gridLayout.addWidget(self.bouton_fermer, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.choix_projet.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/plugins/plugin_rt_2023/image/image/logo_fredon.png\"/></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Filson Pro\',\'Book\'; font-size:14pt; font-weight:600; color:#576b35;\">EXPORT DE BILANS AU FORMAT PDF</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Sélectionner le projet à exporter :</span></p></body></html>"))
        self.choix_projet.setItemText(0, _translate("Dialog", "Xylella_ENR"))
        self.choix_projet.setItemText(1, _translate("Dialog", "Xylella_11F"))
        self.choix_projet.setItemText(2, _translate("Dialog", "Xylella_30A"))
        self.choix_projet.setItemText(3, _translate("Dialog", "Xylella_31A"))
        self.choix_projet.setItemText(4, _translate("Dialog", "Xylella_81A"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Sélectionner le dossier où enregistrer l\'export :</span></p></body></html>"))
        self.choix_chemin.setText(_translate("Dialog", "Parcourir"))
        self.bouton_import.setText(_translate("Dialog", "Lancer l\'export"))
        self.ligne_info.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.bouton_fermer.setText(_translate("Dialog", "Fermer le plugin"))